ConnectionStrings:
    DefinitionDB:"User ID=wf_audit_rw_usr;Password=p@ssw0rd;Host=ngwf-dev-audit.c69sniltamfr.us-east-1.rds.amazonaws.com;Port=5432;Database=wf_audit_v1; Pooling=true; Maximum Pool Size=300;"

PingSts:
    PingBaseUrl: https://qa-trtasso.int.thomson.com
    SecurityServiceUrl: https://dev2.onesourcetax.com/dev2/home-security
    LoneStarUserService: https://dev2.onesourcetax.com/dev2/home-userservice
    StsAgentText: "{cipher}AQICAHiLTTXq8WAJEh75oD8B37GR/xL7SrLJZtkC5HC0f0B94QE8CBReFc5+8cLiS0dRDhe2AAABRzCCAUMGCSqGSIb3DQEHBqCCATQwggEwAgEAMIIBKQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAytcqvqYls7EXR2U6gCARCAgfvd3dQm567jjh3mzl41ayFZjevzb+hZWgiBwnopWHVO3gXoj4wfE5QFh+Msu4aEf9UiRpSpM9kuAAylGwCQKVm1zrj24pIcz2Rp37wA8Ec0V3UdNojvz/yyTbS82zzJM+jqrgQtw0vhvGi3XlJ0dDp4wSpLDkmnGnnWzx6J/G1AHzAVKMPWCHj0kAeuH1z0MMKwq3WxqF68FND8jErZNzIhrrOqCHF+7P2XTf0n5ESMwmeYUgaureDasVZqg2dxqeX65CPVZuQUU3E4wt2lD9E6vt+DAGECg6PrSZb92HsXKQqotx4Ud4yehWxfOVZ9gANqaotAwjamMd82vA=="
    StsUsername: "{cipher}AQICAHiLTTXq8WAJEh75oD8B37GR/xL7SrLJZtkC5HC0f0B94QGS46SjxtinjXbY3oAKDvL5AAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSkRq53nhsYVQkVtQAgEQgCuxQi+ewcA9jiY+/50jCvq+Npw/tNYbtcZjWWqXsMOMqXK7fxadBNmdQOeY"
    StsPassword: "{cipher}AQICAHiLTTXq8WAJEh75oD8B37GR/xL7SrLJZtkC5HC0f0B94QH9YTKqz9laSul37P8a3Tz9AAAAczBxBgkqhkiG9w0BBwagZDBiAgEAMF0GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPOs56oVdxHS7CfiaAgEQgDA6r50o5UUyPE/huF4vgnruOt8tDzjA9jnzIG112XzNn3lv6opKEye+t0XPtvVwSxY="
    GlobalOrgagnizationName: OneSource
    
MiscellaneousConfig:    
    UseSwagger: true
